/*
 * File: web_share_api_client.dart
 * Description: Component and logic definition for web_share_api_client.dart in TelStorage.
 */

import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:dio/dio.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:uuid/uuid.dart';
import '../utils/app_logger.dart';
import 'transfer_queue_service.dart';

class WebShareApiClient {
  static const _r2MinimumTransferTimeout = Duration(minutes: 5);
  static const _r2MaximumTransferTimeout = Duration(minutes: 45);
  static const _assumedMinimumUploadSpeedBytesPerSecond = 64 * 1024;

  /// Resolves the image media type and filename based on magic byte signatures.
  static ({DioMediaType mediaType, String filename}) resolveImageMediaType(
      Uint8List bytes) {
    // 1. JPEG signature: 0xFF, 0xD8, 0xFF
    if (bytes.length >= 3 &&
        bytes[0] == 0xFF &&
        bytes[1] == 0xD8 &&
        bytes[2] == 0xFF) {
      return (
        mediaType: DioMediaType('image', 'jpeg'),
        filename: 'thumbnail.jpg'
      );
    }

    // 2. PNG signature: 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A
    // Defensive: PNG is not currently generated by ThumbnailGenerator but handled if that changes.
    if (bytes.length >= 8 &&
        bytes[0] == 0x89 &&
        bytes[1] == 0x50 &&
        bytes[2] == 0x4E &&
        bytes[3] == 0x47) {
      return (
        mediaType: DioMediaType('image', 'png'),
        filename: 'thumbnail.png'
      );
    }

    // 3. WebP signature: 'RIFF' at 0..3 and 'WEBP' at 8..11
    if (bytes.length >= 12 &&
        bytes[0] == 0x52 &&
        bytes[1] == 0x49 &&
        bytes[2] == 0x46 &&
        bytes[3] == 0x46 &&
        bytes[8] == 0x57 &&
        bytes[9] == 0x45 &&
        bytes[10] == 0x42 &&
        bytes[11] == 0x50) {
      return (
        mediaType: DioMediaType('image', 'webp'),
        filename: 'thumbnail.webp'
      );
    }

    // Fallback: log warning and default safely to JPEG
    AppLogger.w(
      'Thumbnail bytes matched no known image signature, defaulting to image/jpeg',
      tag: 'WebShareApiClient',
    );
    return (
      mediaType: DioMediaType('image', 'jpeg'),
      filename: 'thumbnail.jpg'
    );
  }

  final Dio _dio = Dio(BaseOptions(
    baseUrl: 'https://storage.to/api',
    connectTimeout: const Duration(seconds: 15),
    receiveTimeout: const Duration(seconds: 30),
  ));

  Duration _r2TransferTimeout(int byteLength) {
    final estimatedSeconds =
        (byteLength / _assumedMinimumUploadSpeedBytesPerSecond).ceil();
    final bufferedSeconds = estimatedSeconds * 2;
    final timeoutSeconds =
        _r2MinimumTransferTimeout.inSeconds + bufferedSeconds;

    return Duration(
      seconds: timeoutSeconds
          .clamp(
            _r2MinimumTransferTimeout.inSeconds,
            _r2MaximumTransferTimeout.inSeconds,
          )
          .toInt(),
    );
  }

  Future<String> getOrCreateVisitorToken() async {
    const storage = FlutterSecureStorage();
    String? token = await storage.read(key: 'visitor_token');
    if (token == null) {
      token =
          'visitor_${const Uuid().v4().replaceAll('-', '').substring(0, 16)}';
      await storage.write(key: 'visitor_token', value: token);
    }
    return token;
  }

  /// Streamed upload from a physical on-disk file (0 MB whole-payload RAM buffering).
  Future<Map<String, dynamic>> uploadFileToStorageTo({
    required File file,
    required String transferId,
    required String filename,
    required String mimeType,
    required String visitorToken,
    required void Function(double pct) onProgress,
  }) async {
    if (TransferQueueService.instance.isCancelled(transferId)) {
      throw Exception('Share cancelled by user');
    }

    final fileSize = await file.length();

    final initRes = await _dio.post(
      '/upload/init',
      data: {
        'filename': filename,
        'content_type': mimeType,
        'size': fileSize,
      },
      options: Options(
        headers: {
          'X-Visitor-Token': visitorToken,
          'Content-Type': 'application/json',
        },
      ),
    );

    if (initRes.data['success'] != true) {
      throw Exception(initRes.data['error'] ?? 'Upload initialization failed');
    }

    final type = initRes.data['type'] as String? ?? 'single';
    final r2Key = initRes.data['r2_key'] as String;
    String finalOwnerToken = initRes.data['owner_token'] as String? ?? '';

    if (type == 'single') {
      final uploadUrl = initRes.data['upload_url'] as String;
      await _dio.put(
        uploadUrl,
        data: file.openRead(),
        options: Options(
          sendTimeout: _r2TransferTimeout(fileSize),
          receiveTimeout: _r2TransferTimeout(fileSize),
          headers: {
            Headers.contentLengthHeader: fileSize,
            Headers.contentTypeHeader: mimeType,
          },
        ),
        onSendProgress: (sent, total) {
          final pct = total > 0 ? sent / total : 0.0;
          onProgress(pct);
        },
      );
    } else {
      final uploadId = initRes.data['upload_id'] as String;
      final partSize = initRes.data['part_size'] as int;
      final totalParts = initRes.data['total_parts'] as int;
      final initialUrls = initRes.data['initial_urls'] as Map<String, dynamic>;

      final List<Map<String, dynamic>> completedParts = [];
      final raf = await file.open(mode: FileMode.read);

      try {
        for (var i = 0; i < totalParts; i++) {
          while (TransferQueueService.instance.isPaused(transferId) &&
              !TransferQueueService.instance.isCancelled(transferId)) {
            await Future<void>.delayed(const Duration(seconds: 1));
          }
          if (TransferQueueService.instance.isCancelled(transferId)) {
            throw Exception('Share cancelled by user');
          }

          final partNumber = i + 1;
          final start = i * partSize;
          final length =
              (start + partSize > fileSize) ? fileSize - start : partSize;

          await raf.setPosition(start);
          final partBytes = await raf.read(length);

          String partUrl = initialUrls[partNumber.toString()] as String? ?? '';
          if (partUrl.isEmpty) {
            final partUrlRes = await _dio.post(
              '/upload/parts',
              data: {
                'upload_id': uploadId,
                'part_numbers': [partNumber]
              },
              options:
                  Options(headers: {'Authorization': 'Owner $finalOwnerToken'}),
            );
            if (partUrlRes.data['success'] == true) {
              final partUrls = partUrlRes.data['part_urls'] as List;
              if (partUrls.isNotEmpty) {
                partUrl = partUrls.first['url'] as String;
              }
            }
          }

          if (partUrl.isEmpty) throw Exception('Failed to get part URL');

          final res = await _dio.put(
            partUrl,
            data: Stream.fromIterable([partBytes]),
            options: Options(
              sendTimeout: _r2TransferTimeout(partBytes.length),
              receiveTimeout: _r2TransferTimeout(partBytes.length),
              headers: {
                Headers.contentLengthHeader: partBytes.length,
                Headers.contentTypeHeader: mimeType,
              },
            ),
            onSendProgress: (sent, total) {
              final partPct = total > 0 ? sent / total : 0.0;
              onProgress((i + partPct) / totalParts);
            },
          );

          final etag =
              res.headers.value('etag') ?? res.headers.value('ETag') ?? '';
          if (etag.isEmpty) throw Exception('No ETag');
          completedParts.add({'partNumber': partNumber, 'etag': etag});
        }

        await _dio.post(
          '/upload/complete-multipart',
          data: {'upload_id': uploadId, 'parts': completedParts},
          options: Options(headers: {
            'Authorization': 'Owner $finalOwnerToken',
            'Content-Type': 'application/json'
          }),
        );
      } finally {
        await raf.close();
      }
    }

    final confirmRes = await _dio.post(
      '/upload/confirm',
      data: {
        'filename': filename,
        'size': fileSize,
        'content_type': mimeType,
        'r2_key': r2Key,
      },
      options: Options(headers: {
        'X-Visitor-Token': visitorToken,
        'Content-Type': 'application/json'
      }),
    );

    if (confirmRes.data['success'] != true) {
      throw Exception('Confirmation failed');
    }

    final fileData = confirmRes.data['file'] as Map<String, dynamic>;
    return {
      'id': fileData['id'] as String,
      'share_url': fileData['url'] as String,
      'owner_token': confirmRes.data['owner_token'] as String,
    };
  }

  /// Compatibility wrapper for in-memory byte uploads.
  Future<Map<String, dynamic>> uploadToStorageTo({
    required Uint8List bytes,
    required String transferId,
    required String filename,
    required String mimeType,
    required String visitorToken,
    required void Function(double pct) onProgress,
  }) async {
    final tempDir = Directory.systemTemp.createTempSync('share_upload_');
    final tempFile = File('${tempDir.path}/$filename');
    try {
      await tempFile.writeAsBytes(bytes);
      return await uploadFileToStorageTo(
        file: tempFile,
        transferId: transferId,
        filename: filename,
        mimeType: mimeType,
        visitorToken: visitorToken,
        onProgress: onProgress,
      );
    } finally {
      if (tempDir.existsSync()) {
        try {
          await tempDir.delete(recursive: true);
        } catch (_) {}
      }
    }
  }

  Future<void> deleteShareRemote(String storageToId, String ownerToken) async {
    await _dio.delete(
      '/file/$storageToId',
      options: Options(headers: {'Authorization': 'Owner $ownerToken'}),
    );
  }

  Future<bool> setPasswordRemote(
      String storageToId, String ownerToken, String password) async {
    final res = await _dio.post(
      '/file/$storageToId/password',
      data: {'password': password},
      options: Options(headers: {
        'Authorization': 'Owner $ownerToken',
        'Content-Type': 'application/json'
      }),
    );
    return res.data['success'] == true;
  }

  Future<bool> setExpiryRemote(
      String storageToId, String ownerToken, int days) async {
    final res = await _dio.post(
      '/file/$storageToId/expiry',
      data: {'days': days},
      options: Options(headers: {
        'Authorization': 'Owner $ownerToken',
        'Content-Type': 'application/json'
      }),
    );
    return res.data['success'] == true;
  }

  Future<bool> setMaxDownloadsRemote(
      String storageToId, String ownerToken, int? maxDownloads) async {
    final res = await _dio.post(
      '/file/$storageToId/max-downloads',
      data: {'max_downloads': maxDownloads},
      options: Options(headers: {
        'Authorization': 'Owner $ownerToken',
        'Content-Type': 'application/json'
      }),
    );
    return res.data['success'] == true;
  }

  Future<bool> setVanitySlugRemote(
      String storageToId, String ownerToken, String vanitySlug) async {
    final res = await _dio.post(
      '/file/$storageToId/alias',
      data: {'alias': vanitySlug},
      options: Options(headers: {
        'Authorization': 'Owner $ownerToken',
        'Content-Type': 'application/json'
      }),
    );
    return res.data['success'] == true;
  }

  Future<void> uploadThumbnailRemote(
      String storageToId, String ownerToken, Uint8List imageBytes) async {
    final resolved = resolveImageMediaType(imageBytes);
    final formData = FormData.fromMap({
      'thumbnail': MultipartFile.fromBytes(
        imageBytes,
        filename: resolved.filename,
        contentType: resolved.mediaType,
      ),
    });

    try {
      final res = await _dio.post(
        '/file/$storageToId/thumbnail',
        data: formData,
        options: Options(headers: {
          'Authorization': 'Owner $ownerToken',
          'Content-Type': 'multipart/form-data',
        }),
      );

      if (res.data['success'] != true) {
        throw Exception(res.data['error'] ?? 'Thumbnail upload failed');
      }
    } on DioException catch (e) {
      final responseBody = e.response?.data;
      AppLogger.w(
        'Thumbnail upload rejected by server (${e.response?.statusCode}): $responseBody',
        tag: 'WebShareApiClient',
      );
      // Non-fatal: best-effort thumbnail upload should not disrupt the active share link.
    } catch (e) {
      AppLogger.w('Thumbnail upload failed: $e', tag: 'WebShareApiClient');
    }
  }
}
